site_name: datagnome.de
site_url: !ENV [SITE_URL, "http://127.0.0.1:8000"]
repo_name: romses/Datenzwerg
repo_url: https://github.com/romses/Datenzwerg
dev_addr: 0.0.0.0:8008

theme:
  name: material
  logo: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
  font:
    code: JetBrains Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  grafana:
    base_url: !ENV [GRAFANA_BASE, "https://grafana.datagnome.de/d-solo/" ]
    environment:
      - name: Temperature
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=3
      - name: Air pressure
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=4
      - name: Relative Humidity
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=2
      - name: Absolute humidity
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=15
      - name: Dew point
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=14
      - name: CO2
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=21
      #- name: TVOC
      #  panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=22
      - name: UV index
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=13
      - name: Sound
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=17
    internal:
      - name: Battery voltage
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=1
      - name: Wifi signal
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=5
      #- name: Uptime
      #  panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=31
      - name: UV sensor voltage
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=6
      #- name: Sound sensor RMS voltage
      #  panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=16
      - name: Metadata
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=26

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/romses/Datenzwerg
    - icon: fontawesome/brands/mastodon 
      link: https://chaos.social/@dzoc

extra_css:
  - assets/css/extras.css

nav:
  - Home: index.md
  - sensors.md
  - mastowall.md
  - how_to_build.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: "#"


plugins:
  - search:
  - macros:
  - social:
      cards_layout_options:
        background_color: "#111111"
        color: "#ffffff"
