site_name: Datenzwerg
site_url: !ENV [SITE_URL, "http://127.0.0.1:8000"]
repo_name: romses/Datenzwerg
repo_url: https://github.com/romses/Datenzwerg

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
  font:
    code: JetBrains Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: !ENV [I18N_EN, "/en/"]
      lang: en
    - name: Deutsch
      link: !ENV [I18N_DE, "/de/"]
      lang: de
  
  grafana:
    base_url: !ENV [GRAFANA_BASE, "http://grafana.datagnome.de/grafana/d-solo/f17a6449-84ed-4733-b982-21c0d480c42a/" ]
    environment:
      - name:
          en: Temperature
          de: Temperatur
        panel: datenzwerg-dashboard?orgId=1&panelId=3
      - name: 
          en: Humidity
          de: Luftfeuchtigkeit
        panel: datenzwerg-dashboard?orgId=1&panelId=2
      - name: 
          en: Air pressure
          de: Luftdruck
        panel: datenzwerg-dashboard?orgId=1&panelId=4
      - name:
          en: UV Index
          de: UV Index
        panel: datenzwerg-dashboard?orgId=1&panelId=6
      - name: 
          en: Noise
          de: Lautstärke
        panel: datenzwerg-dashboard?orgId=1&panelId=9
      - name: 
          en: Dew Point
          de: Taupunkt
        panel: datenzwerg-dashboard?orgId=1&panelId=14
      - name: 
          en: Absolute Humidity
          de: Absolute Luftfeuchte
        panel: datenzwerg-dashboard?orgId=1&panelId=16
    internal:
      - name: 
          en: Battery voltage
          de: Batteriespannung
        panel: datenzwerg-dashboard?orgId=1&panelId=1
      - name: 
          en: Wifi signal
          de: Wifisignal
        panel: datenzwerg-dashboard?orgId=1&panelId=5
      - name: 
          en: Uptime
          de: Uptime
        panel: datenzwerg-dashboard?orgId=1&panelId=5

extra_css:
  - assets/css/extras.css

nav:
  - Home: index.md
  - sensors.md
  - how_to_build.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: "#"


plugins:
  - search:
  - macros:
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
