site_name: datagnome.de
site_url: !ENV [SITE_URL, "http://127.0.0.1:8000"]
repo_name: romses/Datenzwerg
repo_url: https://github.com/romses/Datenzwerg
dev_addr: 0.0.0.0:8008

theme:
  name: material
  logo: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
  font:
    code: JetBrains Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: !ENV [I18N_EN, "/en/"]
      lang: en
    - name: Deutsch
      link: !ENV [I18N_DE, "/de/"]
      lang: de

  grafana:
    base_url: !ENV [GRAFANA_BASE, "https://grafana.datagnome.de/d-solo/" ]
    environment:
      - name:
          en: Temperature
          de: Temperatur
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=3
      - name: 
          en: Humidity
          de: Luftfeuchtigkeit
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=2
      - name: 
          en: Air pressure
          de: Luftdruck
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=4
      - name: 
          en: eCO2
          de: eCO2
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=21
      - name: 
          en: TVOC
          de: TVOC
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=22
      - name:
          en: UV index
          de: UV Index
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=18
      - name: 
          en: Sound pressure
          de: Schalldruck
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=17
      - name: 
          en: Dew point
          de: Taupunkt
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=14
      - name: 
          en: Absolute humidity
          de: Absolute Luftfeuchte
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=15
    internal:
      #- name: 
      #    en: Battery voltage
      #    de: Batteriespannung
      #  panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=1
      - name: 
          en: Wifi signal
          de: Wifisignal
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=5
      - name:
          en: eCO2 baseline
          de: eCO2 Baseline
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=23
      - name:
          en: TVOC baseline
          de: TVOC Baseline
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=24
      - name:
          en: UV sensor voltage
          de: UV-Sensorspannung
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=6
      - name:
          en: Sound sensor RMS voltage
          de: Schallsensor-RMS-Spannung
        panel: f17a6449-84ed-4733-b982-21c0d480c42a/?orgId=1&panelId=16

extra_css:
  - assets/css/extras.css

nav:
  - Home: index.md
  - sensors.md
  - mastowall.md
  - how_to_build.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: "#"


plugins:
  - search:
  - macros:
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: de
          name: Deutsch
      reconfigure_material: true
      reconfigure_search: true
  - social:
      cards_layout_options:
        background_color: "#111111"
        color: "#ffffff"

