{
 "title": "Average sensor data",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dew_point\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"absolute_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "eCO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"eco2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tvoc\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uv_index\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> map(fn: (r) => ({r with _value: math.round(x: r._value)}))"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uv_index\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> map(fn: (r) => ({r with _value: math.round(x: r._value)}))"
    }
   ]
  },
  {
   "title": "Sound Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sound_pressure\")\n  |> aggregateWindow(every: 60m, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> map(fn: (r) => ({r with _value: r._value - 15.0}))\n"
    }
   ]
  },
  {
   "title": "WiFi Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_signal\")\n  |> aggregateWindow(every: 60m, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()\n"
    }
   ]
  }
 ]
}