{
 "title": "Datenzwerg Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg_temperature\" or r._measurement == \"temperature\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg_humidity\" or r._measurement == \"humidity\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg_pressure\" or r._measurement == \"pressure\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 10m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  },
  {
   "title": "UV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uv_level\" or r._measurement == \"uv_voltage\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 10m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uv_index\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 10m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  },
  {
   "title": "Sound Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sound_level\" or r._measurement == \"sound_voltage\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 10m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  },
  { "title": "Gnome Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"battery_level\" or r._measurement == \"battery_voltage\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  },
  {
   "title": "WiFi Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"datenzwerg\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg___wifi_signal\" or r._measurement == \"wifi_signal\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> fill(usePrevious: true)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))"
    }
   ]
  }
 ]
}