{
 "title": "Average sensor data",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "UV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uv_voltage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uv_index\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> median(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Sound Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sound_voltage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> mean(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dew_point\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"datenzwerg-downsampled\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"absolute_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> mean(column: \"_value\")\r\n  |> group()"
    }
   ]
  }
 ]
}