{
 "title": "Overview",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "zwerg",
    "label": "Datenzwerg",
    "query": "import \"influxdata/influxdb/schema\"\nimport \"strings\"\n\nschema.tagValues(\n  bucket: \"datagnome\",\n  tag: \"device\"\n)\n  |> filter(fn: (r) => r._value != \"nameme\")\n  |> map(fn: (r) => ({r with _value: strings.title(v: r._value)}))\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "Please check the webpage at [datagnome.de](https://datagnome.de) for\nlatest infos incl location and deployment status, DECT number of the Datenzwerg Operation Center, API access, FAQ etc.\n"
   }
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg_temperature\" or r._measurement == \"temperature\")\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbar " } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg_pressure\" or r._measurement == \"pressure\")\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg_humidity\" or r._measurement == \"humidity\")\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"strings\"\r\nimport \"dict\"\r\n\r\nlocations = [\r\n  \"Bashful\": \"NOC Helpdesk\",\r\n  \"Dopey\": \"DDOS Bar\",\r\n  \"Grumpy\": \"Hall Z\",\r\n  \"Happy\": \"Hall G\",\r\n  \"Hefty\": \"Jugend Assembly\",\r\n  \"Moopsy\": \"Lounge\",\r\n  \"Kinky\": \"Flower Assembly\",\r\n  \"Nerdy\": \"Telnet Assembly\",\r\n  \"Sleepy\": \"POC\",\r\n  \"Sneezy\": \"Hall E\"\r\n]\r\n\r\nfrom(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"absolute_humidity\")\r\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\r\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\r\n  |> group(columns: [\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\r\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "(e)CO2",
   "type": "timeseries",
   "description": "The sensor type is provided, the true \"CO2\" sensors (SCD41) are more accurate than \"eCO2\" (SGP30). We are working on upgrading more gnomes to SCD41.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"bashful\": \"NOC Helpdesk\",\n  \"dopey\": \"DDOS Bar\",\n  \"grumpy\": \"Hall Z\",\n  \"happy\": \"Hall G\",\n  \"hefty\": \"Jugend Assembly\",\n  \"moopsy\": \"Lounge\",\n  \"kinky\": \"Flower Assembly\",\n  \"nerdy\": \"Telnet Assembly\",\n  \"sleepy\": \"POC\",\n  \"sneezy\": \"Hall E\"\n]\n\nco2 = [\n  \"hefty\", \"moopsy\", \"kinky\", \"sleepy\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => (r._measurement == \"eco2\" and not contains(value: r.device, set: co2)) or (r._measurement == \"co2\" and contains(value: r.device, set: co2)))\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device) + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \", \" + (if contains(value: r.device, set: co2) then \"CO2\" else \"eCO2\") + \")\"}))\n"
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "query": "import \"strings\"\r\nimport \"dict\"\r\n\r\nlocations = [\r\n  \"Bashful\": \"NOC Helpdesk\",\r\n  \"Dopey\": \"DDOS Bar\",\r\n  \"Grumpy\": \"Hall Z\",\r\n  \"Happy\": \"Hall G\",\r\n  \"Hefty\": \"Jugend Assembly\",\r\n  \"Moopsy\": \"Lounge\",\r\n  \"Kinky\": \"Flower Assembly\",\r\n  \"Nerdy\": \"Telnet Assembly\",\r\n  \"Sleepy\": \"POC\",\r\n  \"Sneezy\": \"Hall E\"\r\n]\r\n\r\nfrom(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tvoc\")\r\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\r\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\r\n  |> group(columns: [\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\r\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uv_index\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"math\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uv_level\" or r._measurement == \"uv_index\")\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _value: math.round(x: r._value)}))\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "Sound Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sound_pressure\")\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 60m, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({r with _value: r._value - 15.0}))\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"strings\"\r\nimport \"dict\"\r\n\r\nlocations = [\r\n  \"Bashful\": \"NOC Helpdesk\",\r\n  \"Dopey\": \"DDOS Bar\",\r\n  \"Grumpy\": \"Hall Z\",\r\n  \"Happy\": \"Hall G\",\r\n  \"Hefty\": \"Jugend Assembly\",\r\n  \"Moopsy\": \"Lounge\",\r\n  \"Kinky\": \"Flower Assembly\",\r\n  \"Nerdy\": \"Telnet Assembly\",\r\n  \"Sleepy\": \"POC\",\r\n  \"Sneezy\": \"Hall E\"\r\n]\r\n\r\nfrom(bucket: \"datagnome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dew_point\")\r\n  |> map(fn: (r) => ({r with device: if r.device == \"nameme\" then \"kinky\" else r.device}))\r\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\r\n  |> group(columns: [\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\r\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))"
    }
   ]
  },
  {
   "title": "Gnome Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "hex0x" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nfrom(bucket: \"datagnome-raw\")\n  |> range(start: -6h, stop: now())\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"esphome_version\" or r[\"_measurement\"] == \"git_ref\" or r[\"_measurement\"] == \"eco2_baseline\" or r[\"_measurement\"] == \"tvoc_baseline\" or r[\"_measurement\"] == \"uptime\")\n  |> map(fn: (r) => ({r with _value: string(v: r._value)}))\n  |> group(columns: [\"device\"])\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> pivot(rowKey: [\"device\"], columnKey: [\"_measurement\"], valueColumn: \"value\")\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n"
      }
     ]
    },
    {
     "title": "WiFi Signal",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"datenzwerg___wifi_signal\" or r._measurement == \"wifi_signal\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome-raw\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uptime\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "eCO2 Baseline",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "hex0x" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome-raw\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"eco2_baseline\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "TVOC Baseline",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "hex0x" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome-raw\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tvoc_baseline\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"co2\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "eCO2",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "import \"strings\"\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"eco2\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "Battery Voltage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"battery_level\" or r._measurement == \"battery_voltage\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "Battery Drain",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"battery_level\" or r._measurement == \"battery_voltage\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> fill(usePrevious: true)\n  |> difference(initialZero: true)\n  |> filter(fn: (r) => r._value <= 0.0)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "UV Voltage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uv_level\" or r._measurement == \"uv_voltage\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    },
    {
     "title": "Sound RMS Voltage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "Vrms" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nimport \"dict\"\n\nlocations = [\n  \"Bashful\": \"NOC Helpdesk\",\n  \"Dopey\": \"DDOS Bar\",\n  \"Grumpy\": \"Hall Z\",\n  \"Happy\": \"Hall G\",\n  \"Hefty\": \"Jugend Assembly\",\n  \"Moopsy\": \"Lounge\",\n  \"Kinky\": \"Flower Assembly\",\n  \"Nerdy\": \"Telnet Assembly\",\n  \"Sleepy\": \"POC\",\n  \"Sneezy\": \"Hall E\"\n]\n\nfrom(bucket: \"datagnome\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sound_voltage_peak_to_peak\")\n  |> filter(fn: (r) => r.device =~ /(?i)${zwerg:regex}/)\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with device: strings.title(v: r.device)}))\n  |> map(fn: (r) => ({r with device: r.device + \" (\" + dict.get(dict: locations, key: r.device, default: \"?\") + \")\"}))\n"
      }
     ]
    }
   ]
  }
 ]
}