substitutions:
  name: test
  update_interval: 5s
  eco2_baseline: "0x0000"
  tvoc_baseline: "0x0000"

sensor:
  - platform: sgp30
    eco2:
      name: "eCO2"
      id: eco2
      accuracy_decimals: 2
    tvoc:
      name: "TVOC"
      id: tvoc
      accuracy_decimals: 2
    eco2_baseline:
      name: "eCO2 Baseline"
      id: eco2_baseline
    tvoc_baseline:
      name: "TVOC Baseline"
      id: tvoc_baseline
    #compensation:  # compensation turned out to make the measurements unstable AF
    #  humidity_source: bme280_humidity
    #  temperature_source: bme280_temperature
    baseline:
      eco2_baseline: ${eco2_baseline}
      tvoc_baseline: ${tvoc_baseline}
    store_baseline: yes
    update_interval: 1s  # this has to be 1s for according to the sgp30 datasheet
