substitutions:
  name: soundtest

esphome:
  name: "datenzwerg-${name}"
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://JeroenvdV/esphome-influxdb2
    components: [ influxdb2 ]
  - source:
      type: local
      path: components
    components: [ peak_to_peak ]

influxdb2:
  host: !secret influxdb_host
  port: !secret influxdb_port
  orgid: !secret influxdb_orgid
  bucket: !secret influxdb_bucket
  token: !secret influxdb_token
  device: "${name}"

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk

mdns:
  disabled: true

sensor:
  - platform: adc
    pin: A0
    name: "Sound Voltage"
    id: sound_voltage
    update_interval: 5s
    filters:
    - multiply: 3.3

  - platform: peak_to_peak
    sensor: sound_voltage
    name: "Sound Voltage Peak to Peak"
    id: sound_voltage_peak_to_peak
    update_interval: 5s
    accuracy_decimals: 6
    sample_duration: 1s
    filters:
    - multiply: 3.3 # 1.0V to 3.3V
    - multiply: 0.7071 # Peak to Peak to RMS
  
  - platform: template
    name: "Sound Pressure"
    lambda: |-
      const float reference = 94;
      const float amp_gain = 20 * log10(25);
      const float mic_sensitivity = -44;
      return log10(id(sound_voltage_peak_to_peak).state) * 20 + reference - amp_gain - mic_sensitivity;
    unit_of_measurement: "dB"
    accuracy_decimals: 6
    update_interval: 5s
